language: go
os:
  - linux
  - osx
go:
  - "1.10.x"
  - master

before_install:
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $HOME/gopath/src/github.com/tecnologer/uuid
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/tecnologer/uuid/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/tecnologer/uuid
  - cd $HOME/gopath/src/github.com/tecnologer/uuid